<%@ Page Title="Modify Tenant" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Modify_Tenant.aspx.cs" Inherits="PG_Management.Modify_Tenant" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <h2><%: Title %>.</h2>
    <h3>Modify Tenant Details</h3>
    <div class="table-responsive">
        <asp:gridview 
            id="GridView1" 
            runat="server" 
            autogeneratecolumns="true" 
            CssClass="table table-striped table-bordered table-hover table-condensed"
            DataKeyNames="Tenant ID" 
            OnRowEditing="OnRowEditing"
            OnRowCancelingEdit="OnRowCancelingEdit"
            EmptyDataText="No records has been added." 
            AutoGenerateEditButton="true" 
            AutoGenerateDeleteButton="True" 
            EnableSortingAndPagingCallbacks="True"
            OnRowDeleting="OnRowDeleting">
        </asp:gridview>
        
        <%--OnRowUpdating="OnRowUpdating" --%>
    </div>
</asp:Content>
<%-- OnRowDataBound="OnRowDataBound" --%>